### ISSUE TITLE
critical exception occurs on region: chr7:6026294-6026568, program will be stopped.

### ISSUE THREAD

**Issue by asmlgkj** [AstraZeneca-NGS/VarDict#167]
Critical exception occurs on region: chr7:6026294-6026568, program will be stopped.
java.util.concurrent.CompletionException: java.nio.BufferUnderflowException
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
at com.astrazeneca.vardict.collection.DirectThreadExecutor.execute(DirectThreadExecutor.java:8)
at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1618)
at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1843)
at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:46)
at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
at com.astrazeneca.vardict.modes.SimpleMode.notParallel(SimpleMode.java:45)
at com.astrazeneca.vardict.VarDictLauncher.start(VarDictLauncher.java:65)
at com.astrazeneca.vardict.Main.main(Main.java:15)
Caused by: java.nio.BufferUnderflowException
at java.nio.Buffer.nextGetIndex(Buffer.java:510)
at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:680)
at htsjdk.samtools.MemoryMappedFileBuffer.readInteger(MemoryMappedFileBuffer.java:39)
at htsjdk.samtools.AbstractBAMFileIndex.readInteger(AbstractBAMFileIndex.java:443)
at htsjdk.samtools.AbstractBAMFileIndex.query(AbstractBAMFileIndex.java:272)
at htsjdk.samtools.DiskBasedBAMFileIndex.getSpanOverlapping(DiskBasedBAMFileIndex.java:61)
at htsjdk.samtools.BAMFileReader.getFileSpan(BAMFileReader.java:935)
at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:952)
at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:612)
at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538)
at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:400)
at com.astrazeneca.vardict.data.SamView.(SamView.java:21)
at com.astrazeneca.vardict.modules.RecordPreprocessor.nextReader(RecordPreprocessor.java:76)
at com.astrazeneca.vardict.modules.RecordPreprocessor.(RecordPreprocessor.java:50)
at com.astrazeneca.vardict.modules.SAMFileParser.process(SAMFileParser.java:14)
at com.astrazeneca.vardict.modes.AbstractMode.lambda$pipeline$0(AbstractMode.java:47)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
... 8 more

**Comment by asmlgkj** [comment]
related to this 
https://github.com/AstraZeneca-NGS/VarDictJava/issues/341
thanks a lot

**Comment by asmlgkj** [comment]
resort bam wiill solve this
