### ISSUE TITLE
java.lang.NumberFormatException: For input string

### ISSUE THREAD

**Issue by LeilyR** [AstraZeneca-NGS/VarDict#177]
Hi, I am trying to run vardict using the following cmd:

`vardict-java -th 8 -u -I 50 -G ref.fasta -f 0.01  -N TTT -b sample.grouped.sorted.bam  -c 1 -S 2 -E 3 uniq_3col.bed | teststrandbias.R | var2vcf_valid.pl -N TTT -E -f 0.01 > out.vcf`

bed file looks like:
`chr11	102201599	102202102`

bam file is like:
`A00621:654:HJLTTDRXY:2:2111:23333:34483:UMI_ACTGT_GCTCT	83	1	8898	0	6S87M	=	10021	-64	AAATAACGAACCCTAAACCCTAACCCTAAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAACCCTACCCTAACCCTAACCCAAAAAC	F,FF,FF,,F:,,F,,,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	MD:Z:8C1A76	PG:Z:MarkDuplicates	NM:i:2	AS:i:77	XS:i:76	RG:Z:TTT UG:i:22	BX:Z:GCTCT`

and the error I get it:
```
Critical exception occurs on region: 11:102201599-102202102, program will be stopped.
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "36,6"
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at com.astrazeneca.vardict.modes.AbstractMode.pipeline(AbstractMode.java:51)
	at com.astrazeneca.vardict.modes.SimpleMode.processBamInPipeline(SimpleMode.java:103)
	at com.astrazeneca.vardict.modes.SimpleMode.access$000(SimpleMode.java:29)
	at com.astrazeneca.vardict.modes.SimpleMode$VardictWorker.call(SimpleMode.java:86)
	at com.astrazeneca.vardict.modes.SimpleMode$VardictWorker.call(SimpleMode.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

despite the error it still generates a vcf file with its header but no content.

**Comment by LeilyR** [comment]
Update: I solved this issue by using single threaded vardict. (not using vardict-java)

**Comment by PolinaBevad** [comment]
Hi @LeilyR , 
This is decimal format issue (`36,6` as it states in error, should be `36.6`). The problem is not in BAM file but in regional settings of the computer where the program is running. Java version supports EN/US decimal settings where decimal is separated by dot/point. It can be found in your OS settings in number separators/formats sections usually.

**Comment by LeilyR** [comment]
thanks, I will check it out.
